[versions]
com-google-dagger = "2.57.2"
com-squareup-leakcanary = "2.14"
coroutines = "1.10.2"
kotlin = "2.2.21"
org-robolectric = "4.16"

[libraries]
com-android-tools-desugar_jdk_libs = "com.android.tools:desugar_jdk_libs:2.1.5"
com-google-dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "com-google-dagger" }
com-google-dagger-hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "com-google-dagger" }
com-google-dagger-hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "com-google-dagger" }
com-google-truth = "com.google.truth:truth:1.4.5"
com-slack-lint-compose-compose-lint-checks = "com.slack.lint.compose:compose-lint-checks:1.4.2"
com-squareup-leakcanary-leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "com-squareup-leakcanary" }
junit = "junit:junit:4.13.2"
org-jetbrains-kotlinx-kotlinx-collections-immutable = "org.jetbrains.kotlinx:kotlinx-collections-immutable:0.4.0"
org-jetbrains-kotlinx-kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
org-robolectric = { module = "org.robolectric:robolectric", version.ref = "org-robolectric" }

[plugins]
com-android-application = "com.android.application:8.13.0"
com-google-dagger-hilt-android = "com.google.dagger.hilt.android:2.57.2"
com-google-devtools-ksp = "com.google.devtools.ksp:2.3.0"
nl-littlerobots-version-catalog-update = "nl.littlerobots.version-catalog-update:1.0.1"
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
org-jetbrains-kotlin-plugin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
